const app = {
	gulp: require('gulp'),
	browserSync: require('browser-sync').create(),
	fileInclude: require('gulp-file-include'),
	concat: require('gulp-concat'),
	sass: require('gulp-sass')(require('sass')),
	cleanCss: require('gulp-clean-css'),
	autoprefixer: require('gulp-autoprefixer'),
	groupCssMediaQueries: require('gulp-group-css-media-queries'),
	shorthandCss: require('gulp-shorthand'),
	webpackStream: require('webpack-stream'),
	notify: require('gulp-notify'),
	plumber: require('gulp-plumber'),
	newer: require('gulp-newer'),
	avif: require('gulp-avif'),
	webp: require('gulp-webp'),
	imagemin: require('gulp-imagemin'),
	svgSprite: require('gulp-svg-sprite'),
	svgmin: require('gulp-svgmin'),
	cheerio: require('gulp-cheerio'),
	replace: require('gulp-replace'),
	fonter: require('gulp-fonter'),
	ttf2woff2: require('gulp-ttf2woff2'),
	del: require('del'),
	htmlmin: require('gulp-htmlmin'),
	webpHtml: require('gulp-webp-html'),
	webpCss: require('gulp-webp-css'),
}

module.exports = app;